"""direct purchases

Revision ID: 1e09fb9195fc
Revises: e14e06abad3e
Create Date: 2026-10-10 01:10:08.365322
"""

import sqlalchemy as sa
from alembic import op

revision = "1e09fb9195fc"
down_revision = "e14e06abad3e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "direct_purchase",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("code", sa.String(length=32), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("state_id", sa.SmallInteger(), nullable=True),
        sa.Column("state", sa.String(length=64), nullable=True),
        sa.Column("cpv_code", sa.String(length=16), nullable=True),
        sa.Column("cpv_name", sa.Text(), nullable=True),
        sa.Column("buyer_cui", sa.BigInteger(), nullable=True),
        sa.Column("buyer_text", sa.Text(), nullable=True),
        sa.Column("supplier_cui", sa.BigInteger(), nullable=True),
        sa.Column("supplier_text", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_value_ron", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("closing_value", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("source_document_id", sa.BigInteger(), nullable=False),
        sa.Column("parser_version", sa.SmallInteger(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["buyer_cui"],
            ["entity.cui"],
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_document.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_cui"],
            ["entity.cui"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_direct_purchase_buyer_cui"), "direct_purchase", ["buyer_cui"], unique=False
    )
    op.create_index(op.f("ix_direct_purchase_code"), "direct_purchase", ["code"], unique=False)
    op.create_index(
        op.f("ix_direct_purchase_cpv_code"), "direct_purchase", ["cpv_code"], unique=False
    )
    op.create_index(
        op.f("ix_direct_purchase_finalized_at"), "direct_purchase", ["finalized_at"], unique=False
    )
    op.create_index(
        op.f("ix_direct_purchase_supplier_cui"), "direct_purchase", ["supplier_cui"], unique=False
    )
    op.add_column("source_document", sa.Column("request_body", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_document", "request_body")
    op.drop_index(op.f("ix_direct_purchase_supplier_cui"), table_name="direct_purchase")
    op.drop_index(op.f("ix_direct_purchase_finalized_at"), table_name="direct_purchase")
    op.drop_index(op.f("ix_direct_purchase_cpv_code"), table_name="direct_purchase")
    op.drop_index(op.f("ix_direct_purchase_code"), table_name="direct_purchase")
    op.drop_index(op.f("ix_direct_purchase_buyer_cui"), table_name="direct_purchase")
    op.drop_table("direct_purchase")
    # ### end Alembic commands ###
