"""initial tables

Revision ID: e14e06abad3e
Revises:
Create Date: 2026-10-09 18:03:38.405233
"""

import sqlalchemy as sa
from alembic import op

revision = "e14e06abad3e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Diacritic-insensitive, typo-tolerant name search ("Barzava" finds "Bârzava").
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_run",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("job", sa.String(length=64), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_run_job"), "job_run", ["job"], unique=False)
    op.create_table(
        "source_document",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256"),
    )
    op.create_index(op.f("ix_source_document_source"), "source_document", ["source"], unique=False)
    op.create_table(
        "entity",
        sa.Column("cui", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("county", sa.String(length=64), nullable=True),
        sa.Column("locality", sa.String(length=128), nullable=True),
        sa.Column("parent_cui", sa.BigInteger(), nullable=True),
        sa.Column("source_document_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_cui"],
            ["entity.cui"],
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_document.id"],
        ),
        sa.PrimaryKeyConstraint("cui"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entity")
    op.drop_index(op.f("ix_source_document_source"), table_name="source_document")
    op.drop_table("source_document")
    op.drop_index(op.f("ix_job_run_job"), table_name="job_run")
    op.drop_table("job_run")
    # ### end Alembic commands ###
