"""award notices

Revision ID: 55da399e58f0
Revises: de6979c2589b
Create Date: 2026-10-10 20:04:29.054202
"""

import sqlalchemy as sa
from alembic import op

revision = "55da399e58f0"
down_revision = "de6979c2589b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "award_notice",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("notice_no", sa.String(length=32), nullable=True),
        sa.Column("notice_type_id", sa.SmallInteger(), nullable=True),
        sa.Column("procedure_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("buyer_cui", sa.BigInteger(), nullable=True),
        sa.Column("buyer_text", sa.Text(), nullable=True),
        sa.Column("cpv_code", sa.String(length=16), nullable=True),
        sa.Column("cpv_name", sa.Text(), nullable=True),
        sa.Column("contract_type_id", sa.SmallInteger(), nullable=True),
        sa.Column("contract_type", sa.String(length=64), nullable=True),
        sa.Column("procedure_type_id", sa.SmallInteger(), nullable=True),
        sa.Column("procedure_type", sa.String(length=128), nullable=True),
        sa.Column("procedure_state_id", sa.SmallInteger(), nullable=True),
        sa.Column("procedure_state", sa.String(length=64), nullable=True),
        sa.Column("assignment_type_id", sa.SmallInteger(), nullable=True),
        sa.Column("assignment_type", sa.String(length=64), nullable=True),
        sa.Column("value_ron", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("is_utility", sa.Boolean(), nullable=True),
        sa.Column("has_subsequent_contracts", sa.Boolean(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_document_id", sa.BigInteger(), nullable=False),
        sa.Column("parser_version", sa.SmallInteger(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["buyer_cui"],
            ["entity.cui"],
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_award_notice_buyer_cui"), "award_notice", ["buyer_cui"], unique=False)
    op.create_index(op.f("ix_award_notice_cpv_code"), "award_notice", ["cpv_code"], unique=False)
    op.create_index(op.f("ix_award_notice_notice_no"), "award_notice", ["notice_no"], unique=False)
    op.create_index(
        op.f("ix_award_notice_procedure_id"), "award_notice", ["procedure_id"], unique=False
    )
    op.create_index(
        op.f("ix_award_notice_published_at"), "award_notice", ["published_at"], unique=False
    )
    op.create_table(
        "award_contract",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("notice_id", sa.BigInteger(), nullable=False),
        sa.Column("contract_no", sa.Text(), nullable=True),
        sa.Column("contract_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("kind", sa.SmallInteger(), nullable=True),
        sa.Column("lots", sa.Text(), nullable=True),
        sa.Column("value", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("value_ron", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("min_offer_ron", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("max_offer_ron", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("modified_count", sa.Integer(), nullable=True),
        sa.Column("source_document_id", sa.BigInteger(), nullable=False),
        sa.Column("parser_version", sa.SmallInteger(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["notice_id"],
            ["award_notice.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_award_contract_contract_date"), "award_contract", ["contract_date"], unique=False
    )
    op.create_index(
        op.f("ix_award_contract_notice_id"), "award_contract", ["notice_id"], unique=False
    )
    op.create_table(
        "award_winner",
        sa.Column("contract_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("supplier_cui", sa.BigInteger(), nullable=True),
        sa.Column("supplier_text", sa.Text(), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("source_document_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["contract_id"], ["award_contract.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_document.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_cui"],
            ["entity.cui"],
        ),
        sa.PrimaryKeyConstraint("contract_id", "position"),
    )
    op.create_index(
        op.f("ix_award_winner_supplier_cui"), "award_winner", ["supplier_cui"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_award_winner_supplier_cui"), table_name="award_winner")
    op.drop_table("award_winner")
    op.drop_index(op.f("ix_award_contract_notice_id"), table_name="award_contract")
    op.drop_index(op.f("ix_award_contract_contract_date"), table_name="award_contract")
    op.drop_table("award_contract")
    op.drop_index(op.f("ix_award_notice_published_at"), table_name="award_notice")
    op.drop_index(op.f("ix_award_notice_procedure_id"), table_name="award_notice")
    op.drop_index(op.f("ix_award_notice_notice_no"), table_name="award_notice")
    op.drop_index(op.f("ix_award_notice_cpv_code"), table_name="award_notice")
    op.drop_index(op.f("ix_award_notice_buyer_cui"), table_name="award_notice")
    op.drop_table("award_notice")
    # ### end Alembic commands ###
